### ISSUE TITLE
Nick Copy `Don't close this even if you don't want to merge it`

### ISSUE THREAD

**Issue by kennarddh** [DogeMultiverse/watermelonbot#35]
Troll Command to rename everyone

## Draft

```
create a command in melon py to change everyone nick name to breadxxxx but with random number replace x with random number. but create a db collection to store the previous nick. also make a command to undo that so bread will be confused. i hope bread doesnt see this.... 
```

hmm i dont want this just for bread so lets do this

# RFC (Troll Command To Rename Everyone to one player but with random number replaced)

## Command Structure

- Parameter structure: `{type:name:default}` if there is default then the parameter is optional
- `nickCopy`: `{prefix}{commandName} {user:userToBeCopied} {char:characterInNickOrUsernameToReplaceWithNumber:x} {boolean:shouldRenameTargetUser:false} {boolean:shouldRenameBot:false}`
- `nickCopyReset`: `{prefix}{commandName}`

## Condition

- If the config with id `nick-copy` exist that mean there is pending nick copy.
- `nickCopy`: Should not run if there is any pending nick copy.
- `nickCopyReset`: Should not run if there is no any pending nick copy

## Save Data

- Save data with document maybe in new collection called config and give special id `nick-copy`
- The fields are `id`, `targetUserId`

### Nickname Reset

- Save all current user nickname in db collection `nick-copy-rollback`
- The fields are `id` (user.id), `nickname` (user.nick || null)

**Comment by alexpvpmindustry** [comment]
hopefully bread sees this

**Comment by kennarddh** [comment]
lol

**Comment by kennarddh** [comment]
ill write the full spec later

**Comment by kennarddh** [comment]
> hopefully bread sees this

he have a github account?

**Comment by kennarddh** [comment]
wait lol here i use nick copy for the pr i use copy nick
