### ISSUE TITLE
Recentralization and Prevention of lack of stability in the system

### ISSUE THREAD

**Issue by the43rddev** [DogeMultiverse/watermelonbot#51]
why is there 7 branches

**Comment by the43rddev** [comment]
oi mate we gotta re centralize this whole crap mate @alexpvpmindustry

**Comment by the43rddev** [comment]
@alexpvpmindustry I would like to issue a temporary collab role in order to sort out and clean out stuffs for 2 weeks

**Comment by kennarddh** [comment]
@the43rddev what is `Recentralization and Prevention of lack of stability in the system`?

**Comment by the43rddev** [comment]
a reconsolidation of the bot, tldr: code maintenance

**Comment by the43rddev** [comment]
no not really, github maintenance, sorry for the confusion

**Comment by alexpvpmindustry** [comment]
Thx for the feedback. Deleted all the branches.

If you wan to contribute, fork n make pr.

**Comment by the43rddev** [comment]
you are welcome mate

**Comment by the43rddev** [comment]
wait, what about the mindus command branch??
