### ISSUE TITLE
Add FAQ command

### ISSUE THREAD

**Issue by kennarddh** [DogeMultiverse/watermelonbot#54]
- How to be mod/admin
- How to register

Just that for now ig

## Command

- `w?faq [page=1]` show all faq 10 each page
- `w?faq "mod"` show the nearest available faq like search

**Comment by kennarddh** [comment]
> mmm this is in the text channel #info or something

yea... ik but people dont read it...

**Comment by alexpvpmindustry** [comment]
i think the implementation for this command is just to point to the #info channel

this way we don't have to retype the faq again
